/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "wrdxngjzffmsrnnemmel"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndyZHhuZ2p6ZmZtc3JubmVtbWVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA3OTA2NDIsImV4cCI6MjA4NjM2NjY0Mn0.sitVIbcQgq8eKdhK3R8TzFa-Nk-w17KL4jbKsGKnk8E"